### PR TITLE
metadata builder changes for missing fields

### PR DESCRIPTION
**Pull request by dhruv-bansal**
first, pull a request for a fix - https://github.com/xmidt-org/talaria/issues/186

CC @schmidtw

### CODE REVIEW

**Comment by Sachin4403** [comment]
Hello Team,

Once this PR is merged we need to  upgrade this module version in talaria.

**Review by johnabass — APPROVED** [review]
👍

**Comment by Sachin4403** [comment]
Hello @kristinapathak 
Could you please merge this PR?

**Comment by denopink** [comment]
👆 can we merge this @johnabass

**Pull request merged**
